version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graus
      MYSQL_USER: graus
      MYSQL_PASSWORD: graus
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
